include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Organização e consistência
    directives_ordering: true
    always_declare_return_types: true
    type_annotate_public_apis: true

    # Imutabilidade e const-correctness
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Boas práticas de widgets
    use_key_in_widget_constructors: true
    sort_child_properties_last: true

    # Qualidade de código
    avoid_print: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_unused_constructor_parameters: true
    avoid_unnecessary_containers: true