// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuZwE8xVSWckbL5vzAzzP6G3Dd0hrVkTc',
    appId: '1:238737239859:web:630fe72e7a5cc160299846',
    messagingSenderId: '238737239859',
    projectId: 'sicredo-34f2e',
    authDomain: 'sicredo-34f2e.firebaseapp.com',
    storageBucket: 'sicredo-34f2e.firebasestorage.app',
    measurementId: 'G-RYF0C5YL0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoLUG2xrB8C58LX3lltYQ0IDUGGJXs1_Q',
    appId: '1:238737239859:android:7bdcfa3d1eb7a6f3299846',
    messagingSenderId: '238737239859',
    projectId: 'sicredo-34f2e',
    storageBucket: 'sicredo-34f2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq19HI5x7BdQ_ZnLTFqeySgZkaSR-8_hs',
    appId: '1:238737239859:ios:a4c77c7fba704a5b299846',
    messagingSenderId: '238737239859',
    projectId: 'sicredo-34f2e',
    storageBucket: 'sicredo-34f2e.firebasestorage.app',
    iosClientId: '238737239859-bgva5stf1mqaohlun4dtfhgirt24di6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.sicredo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq19HI5x7BdQ_ZnLTFqeySgZkaSR-8_hs',
    appId: '1:238737239859:ios:a4c77c7fba704a5b299846',
    messagingSenderId: '238737239859',
    projectId: 'sicredo-34f2e',
    storageBucket: 'sicredo-34f2e.firebasestorage.app',
    iosClientId: '238737239859-bgva5stf1mqaohlun4dtfhgirt24di6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.sicredo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuZwE8xVSWckbL5vzAzzP6G3Dd0hrVkTc',
    appId: '1:238737239859:web:231cf2eace60b6a1299846',
    messagingSenderId: '238737239859',
    projectId: 'sicredo-34f2e',
    authDomain: 'sicredo-34f2e.firebaseapp.com',
    storageBucket: 'sicredo-34f2e.firebasestorage.app',
    measurementId: 'G-1E9NG1V3WH',
  );
}
